### ISSUE TITLE
STM32 Support

### ISSUE THREAD

**Issue by Rasoul77** [doayee/RN52#2]
First of all, thanks for this amazingly easy to use library!
I am currently using STM32 Blue Pill board to develop my own Bluetooth receiver project. The RN52 Lib is a very convenient lib when being used with Arduino boards, but unfortunately it doesn't work on STM32. Could you please help me to find out which places in the code I need to modify to make it be compiled and run on STM32 based boards such as Blue Pill?

**Comment by doayee** [comment]
Hi,

Unfortunately we do not support and don't intend to support STM32 with this library - we also have no experience with this 'Blue Pill' board you are using. However happy to make some suggestions... are you using the STM32duino core. This appears to have an implementation of SoftwareSerial and that is what the RN52 library is based upon, with our own functions for the RN52 added in. 

Doayee
